shader_type canvas_item;

uniform vec3 sparkle_color: source_color;
uniform float contrast : hint_range(0.0, 10.0) = 1.0;
uniform float bias : hint_range(-1.0, 1.0) = 1.0;
uniform float scale : hint_range(0.0, 1.0) = 1.0;

vec2 random(vec2 uv){
    uv = vec2( dot(uv, vec2(127.1,311.7) ),
               dot(uv, vec2(269.5,183.3) ) );
    return -1.0 + 2.0 * fract(sin(uv) * 43758.5453123);
}

float noise(vec2 uv) {
    vec2 uv_index = floor(uv);
    vec2 uv_fract = fract(uv);

    vec2 blur = smoothstep(0.0, 1.0, uv_fract);

    return mix( mix( dot( random(uv_index + vec2(0.0,0.0) ), uv_fract - vec2(0.0,0.0) ),
                     dot( random(uv_index + vec2(1.0,0.0) ), uv_fract - vec2(1.0,0.0) ), blur.x),
                mix( dot( random(uv_index + vec2(0.0,1.0) ), uv_fract - vec2(0.0,1.0) ),
                     dot( random(uv_index + vec2(1.0,1.0) ), uv_fract - vec2(1.0,1.0) ), blur.x), blur.y) + 0.5;
}

void fragment() {
	vec2 st = FRAGCOORD.xy;
	vec2 pos = vec2(st*scale) * TIME/100.0;
	float intensity = pow(noise(pos), contrast) + bias;
	if(intensity > 0.5){
		COLOR = vec4(sparkle_color * COLOR.rgb, COLOR.a);
	}
}

//void light() {
//	// Called for every pixel for every light affecting the CanvasItem.
//	// Uncomment to replace the default light processing function with this one.
//}
